### PR TITLE
New QueueLock plugin to only allow one job queued

### PR DESCRIPTION
**Pull request by raykrueger**
This relies on the recently committed "before_enqueue" feature. I've created an alternate lock plugin called QueueLock, that only allows one job to be in the queue at a time.

This fixes a use case for us where even if we only allow one instance of the job (with the same args) to run at a time, we don't want them to run in rapid fire succession if the workers got busy with something else.

I built this by essentially duplicating the Lock plugin and modifying it's behavior. I'm submitting it as an addition to the Lock plugin since it seems to be the right namespace rather than trying  to create an all new plugin.

I was also wondering if perhaps the Lock plugin should really just be modified to work this way instead?

Thanks,
-Ray

### CODE REVIEW

**Comment by defunkt** [comment]
Looks good! resque-lock is so small, I think QueueLock might work best as its own plugin.

**Comment by raykrueger** [comment]
ok, I'll spin it off. It's been working great for us.
Except when Resque dirty exits and leaves the lock behind. (Same problem with resque-lock)

**Comment by defunkt** [comment]
On second thought, I agree with your final point:

> I was also wondering if perhaps the Lock plugin should really just be modified to work this way instead?

Let's do it.

**Comment by raykrueger** [comment]
lol ok I'll see about knocking that out tonight.

**Comment by defunkt** [comment]
Just push'd your patch. However the tests are failing:

```
Loaded suite test/queue_lock_test
Started
.FF
Finished in 0.019754 seconds.

  1) Failure:
test_lock(QueueLockTest) [test/queue_lock_test.rb:40]:
<1> expected but was
<3>.

  2) Failure:
test_version(QueueLockTest) [test/queue_lock_test.rb:34]:
<false> is not true.

3 tests, 5 assertions, 2 failures, 0 errors
```

Are you seeing this as well?

**Comment by raykrueger** [comment]
My tests in our queue-lock branch (at 15f1e70cd2) are all passing.

LockTest
    test_lint                                                             PASS
    test_lock                                                             PASS
    test_version                                                          PASS
QueueLockTest
    test_lint                                                             PASS
    test_lock                                                             PASS
    test_version                                                          PASS

I also just pulled defunkt/master and merged and they still pass.

**Comment by defunkt** [comment]
15f1e70cd29e672ded93d41eaedbf3e4814f4f9e is not passing for me. Shady!

What version of Redis are you on? I'm at 2.0.4 locally, Ruby 1.8.7, Resque 1.17.1

**Comment by raykrueger** [comment]
If test_version(QueueLockTest) is failing that means we're not on the same resque version.

That code relies on the before_enque_hooks addition in:
https://github.com/defunkt/resque/commit/aa24424c9484858c51194eb903f30c68fa0c88cb#lib/resque/plugin.rb

It looks like you haven't cut a resque release that includes that yet :(

**Comment by defunkt** [comment]
I know a guy who can fix that. Gimmie a few.

**Comment by defunkt** [comment]
Okay, 1.18 is out

**Comment by defunkt** [comment]
And now all the tests pass. Woot.

**Comment by defunkt** [comment]
ship'd

**Comment by raykrueger** [comment]
Are you planning on just merging QueueLock in or actually replacing Lock?

**Comment by raykrueger** [comment]
haha nevermind :P

**Pull request closed without merging**
